# Generated by Django 3.0.7 on 2022-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ame',
            field=models.CharField(max_length=1000),
        ),
    ]
