# Generated by Django 3.0.7 on 2022-04-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220423_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='ame',
            new_name='name',
        ),
    ]
